layout_spectrum: 1
color:
  saturation: 0.4659498
  brandStrength: 0.1162919
  lightness: 0.4193548
  rhythmicContrast: 0.5985663
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.2939068
name: 'Pureforme '
